Youtube mimick
jdmartinez1062/Basic-HTML-Page-Structure pull request #1
Opened 2019-08-14 20:36 UTC by jdmartinez1062

2019-08-15 17:47 UTC, mosaaleb requested changes
### Impressive work @mariobarrioss, @jdmartinez1062 :clap:

The UI looks very nice, yet there are some requirements needs to be met before moving on.

- [x] The project has a descriptive README.md

- [x] Files not related to the project should not be commited and added to .gitignore (e.g. `.DS_Store`)

- [x] There are some errors from your [html validator](https://validator.w3.org/). Let's fix these errors. 

**TIP** You can use html lint plugin in your preferred text editor, and it will catch these errors for you while you coding. I prefer using [html lint](https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint) on vscode. There is also a style lint plugins for css files.

- [x] For the page to be more alike the original page, let's add a **comments** section.

Also please see my comments below.


Please handle these requirements and submit a new code review.

#### Happy Coding :computer:

2019-08-15 17:47 UTC, mosaaleb commented on Index.HTML
> +        </div>
The user avatar image is broken on live. We can fix it by removing the `/` to be `Icons/Captura.PNG`. [See this for more info](http://www.scriptingok.com/tutorial/HTML-links-2)

2019-08-15 17:47 UTC, mosaaleb commented on Index.HTML
> +                <div id="upavatar-info-div">
The same concept of relative paths for this avatar.

2019-08-15 17:47 UTC, mosaaleb commented on Index.HTML
> +            <button type="submit" id="search-button">
- **`[OPTIONAL]`** For simple components like search field, we can ignore the `<form>` tag. [more](https://stackoverflow.com/questions/3294572/is-input-well-formed-without-a-form)

2019-08-15 17:47 UTC, mosaaleb commented on Index.HTML
> +                <img id="autoplay" src="Thumbnails/autoplay.png" alt="Autoplay mimick">
**`[OPTIONAL]`** We can use `<aside>` for the recommended videos for more semantic tags.

2019-08-17 07:22 UTC, samgaco commented
### Hi @jdmartinez1062  and @mariobarrioss :hand: 

### Everything is looking good, just a few more things before we can give you the approval:

* There is still one error left showing in the [validator](https://validator.w3.org).
* You added a comments section, but a horizontal scrolling bar is showing now, it shouldn't show.
* [SUGGESTION] You could add also your contacts to the readme file and a live demo of the site using https://raw.githack.com/ .

### Please :pray: work on these points and submit back for another code review when you are done :muscle: Regards!

2019-08-20 03:12 UTC, Ispirett requested changes
Really Great Job with Changes @Team your project is a go :100: 
But before this can compete you need a  to resolve the stickler issues.

2019-08-21 21:58 UTC, samgaco commented
### @jdmartinez1062 and @mariobarrioss congratulations :tada: your project is approved :clap: 

#### You can now merge to the master branch and submit the project completion form. Keep up the good work for your next projects!! :muscle:

2019-08-22 15:16 UTC, merged